version: '3.8'
services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 4001:3000
    volumes:
      - .:/code
    depends_on:
      - db
      - rdb
    env_file:
      - .dev.env

  # client:
  #   container_name: client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.client
  #     target: dev
  #   ports:
  #     - '5000:5000'
  #     - '35729:35729'
  #   volumes:
  #     - ./client:/usr/src/app
  #   depends_on:
  #     - flask

  db:
    container_name: db
    image: 'postgres:13'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 6432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=snakes
      - POSTGRES_DB=flask-app

  rdb:
    container_name: rdb
    image: 'redis:alpine'
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - 6379:6379
    restart: always

volumes:
  postgres_data:
  redis-data:
